name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Odin
        uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: latest

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libxrandr-dev libinerama-dev libxcursor-dev libxi-dev

      - name: Build Project
        run: odin build . -out:gameoflife
